### PR TITLE
ailment indexjs setup

### PR DESCRIPTION
**Pull request by jalynjenkins**
Setup Ailment indexjs
Data is pulling from API and showing a list of ailments on the page

### CODE REVIEW

**Review by zm102905 — COMMENTED** [review]
Looks good. Maybe just change the links on the header to a single link.

**Review by zm102905 — APPROVED** [review]
Looks great. I would change the "ailment" links on the homepage to a single link.

**Comment by jjmirwaldjr** [comment]
Looks good, reviewed the code and i approve.

**Review by jjmirwaldjr — APPROVED** [review]
Mergeing the code

**Pull request merged**
