### PR TITLE
Treatmentbranch

### PR DESCRIPTION
**Pull request by zm102905**
fixed text on banner to display in a single line on all pages

### CODE REVIEW

**Review by jjmirwaldjr — APPROVED** [review]
I have reviewed the code, Looks good

**Comment by acbluem** [comment]
I can't preview it as it still brings up old code. Zach, are you making new branches for each thing you work on?

**Comment by zm102905** [comment]
> 

No, it's all under that one branch

**Comment by zm102905** [comment]
> 

I added that one piece of code that displays the text in a single line. It works I tested it one my 15 inch and 24 inch monitor

**Pull request merged**
